const PARTY_CATEGORIES = [
  "All",
  "Deep conversation",
  "Playful",
  "Reflection",
  "Gratitude",
  "Dreams",
  "Repair",
  "Creative"
];

const PARTY_PREFILLED_PROMPTS = [
  { category: "Deep conversation", text: "What is something you wish more people understood about how you experience friendship?" },
  { category: "Deep conversation", text: "What do you usually hide when you are trying to seem fine?" },
  { category: "Deep conversation", text: "What is a question you have wanted someone to ask you lately?" },
  { category: "Deep conversation", text: "What kind of support feels good to receive, and what kind accidentally makes things worse?" },
  { category: "Deep conversation", text: "What are you learning about the way you love people?" },
  { category: "Deep conversation", text: "What is something you are proud of surviving but rarely talk about?" },
  { category: "Deep conversation", text: "When do you feel most like your real self around other people?" },
  { category: "Reflection", text: "Share one belief you used to hold strongly that has softened or changed." },
  { category: "Reflection", text: "What pattern in your life are you trying to outgrow right now?" },
  { category: "Reflection", text: "What did your younger self need to hear that you can say out loud now?" },
  { category: "Reflection", text: "What part of your personality gets misunderstood most often?" },
  { category: "Reflection", text: "What is a quiet win from this month that deserves to be witnessed?" },
  { category: "Reflection", text: "What helps you return to yourself after you have been overwhelmed?" },
  { category: "Gratitude", text: "Tell someone here one specific way they have made your life easier or brighter." },
  { category: "Gratitude", text: "Share appreciation for someone here without mentioning achievements or productivity." },
  { category: "Dreams", text: "Describe a version of your life five years from now that would make you feel deeply alive." },
  { category: "Dreams", text: "What kind of home, community, or rhythm are you craving more of?" },
  { category: "Dreams", text: "What creative project, skill, or life change keeps tugging at your attention?" },
  { category: "Dreams", text: "What would you try if embarrassment was temporarily impossible?" },
  { category: "Dreams", text: "What is a dream you want friends to gently keep asking you about?" },
  { category: "Repair", text: "What is one thing that helps you feel safe during a hard conversation?" },
  { category: "Repair", text: "Finish the sentence: 'When I get defensive, underneath it I am often feeling...'" },
  { category: "Repair", text: "What is a small repair someone can offer you after a misunderstanding?" },
  { category: "Repair", text: "Share one way friends can tell you are upset before you say it directly." },
  { category: "Repair", text: "What is a boundary you are practicing naming more clearly?" },
  { category: "Repair", text: "Each person names one behavior that helps them receive feedback without shutting down." },
  { category: "Reflection", text: "Offer a 20-second hand squeeze, shoulder squeeze, or no-touch eye contact. Everyone chooses their own comfort level." },
  { category: "Playful", text: "Pair up and ask, 'Would a hug, high five, fist bump, or no touch feel best right now?'" },
  { category: "Reflection", text: "Make a consent circle: each person names one kind of platonic touch they enjoy and one they do not want today." },
  { category: "Gratitude", text: "Try a back-to-back breathing reset for one minute, with an opt-out option of sitting nearby." },
  { category: "Playful", text: "Create a group handshake that includes only gestures everyone enthusiastically agrees to." },
  { category: "Gratitude", text: "Do a consent-based appreciation hug line where each person can choose hug, wave, hand over heart, or skip." },
  { category: "Reflection", text: "Sit shoulder-to-shoulder with a willing friend for one song, or sit nearby if touch is not wanted." },
  { category: "Playful", text: "Each person invents a fake award for someone in the group and gives a one-sentence acceptance speech for them." },
  { category: "Playful", text: "Everyone shares an oddly specific thing they find delightful." },
  { category: "Playful", text: "Choose one person to be interviewed like a beloved local legend for three minutes." },
  { category: "Playful", text: "Everyone writes a compliment on a note or phone, shuffles them, then guesses who each one is about." },
  { category: "Playful", text: "Describe your current mood as a weather report, including temperature, forecast, and travel advisory." },
  { category: "Creative", text: "Build a tiny group playlist: each person adds one song and says what moment it belongs to." },
  { category: "Creative", text: "Create a shared bucket list with one cozy, one silly, one brave, and one generous activity." },
  { category: "Creative", text: "Each person contributes one line to a poem." },
  { category: "Creative", text: "Design a care menu for the group: low-energy hangouts, crisis support, celebration rituals, and repair rituals." },
  { category: "Creative", text: "Take five quiet minutes to make something small for another person: a doodle, voice memo, playlist title, or note." },
  { category: "Deep conversation", text: "What kind of attention makes you feel cherished rather than watched?" },
  { category: "Gratitude", text: "Name something someone here does naturally that makes the room feel more human." },
  { category: "Reflection", text: "What is a part of you that is asking for more tenderness lately?" },
  { category: "Dreams", text: "If your friendships became more honest this year, what would change first?" }
].map((prompt, index) => ({
  ...prompt,
  id: `prefilled-${index + 1}`,
  source: "prefilled"
}));
